### ISSUE TITLE
`has_feature` with multiple args

### ISSUE THREAD

**Issue by jak3-yoroi** [alem0lars/fizzy#38]
It should be nice if `has_feature` function has more than one argument.
Doing so in a template file (*.tt*) you can specify more feature at once like `if has_feature(X,Y...)`.

**Comment by alem0lars** [comment]
The current method is: `has_feature?`, not `has_feature`.

Go ahead, make pull request for changing the signature of:

```ruby
def has_feature?(feature_name)
```

To:

```ruby
def has_feature?(*feature_names)
```

The changes should be backward compatible.
